spring:
  main:
    allow-circular-references: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    properties:
      hibernate:
#        hbm2ddl:
#          auto: validate
        dialect: org.hibernate.dialect.PostgreSQLDialect
        transaction:
          jta:
            platform: enable
    hibernate:
      ddl-auto: create-drop #update
    generate-ddl: true
    show-sql: true
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost:5432}/${POSTGRES_DB_NAME:account_db}
    username: postgres
    password: postgres
    hikari:
      schema: account_schema
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS account_schema
      connection-timeout: 10000
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml
  application:
    name: mc-account
#  kafka:
#    bootstrap-servers: localhost:9092
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://${EUREKA-HOST:localhost}:8761/eureka/
    fetch-registry: true
  instance:
    hostname: ${mc-account:localhost}
    prefer-ip-address: true
#    instance-id: ${spring.application.name}:${random.uuid}
#app:
#  kafka:
#    userRegistration: ""
#    accountChanges: ""
#    groupId: ""
server:
  port: 8080